# Generated by Django 3.2.25 on 2024-04-29 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.coursetable')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.usertable')),
            ],
        ),
    ]
