# Generated by Django 3.2.25 on 2024-04-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_courseta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseTA',
        ),
    ]
