# Generated by Django 3.2.25 on 2024-05-07 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_delete_courseta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtable',
            name='sectionId',
        ),
        migrations.RemoveField(
            model_name='sectiontable',
            name='userCourseJoinId',
        ),
        migrations.AddField(
            model_name='labtable',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='sectiontable',
            name='time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='UserSectionJoinTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.sectiontable')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='UserLabJoinTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.labtable')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.usertable')),
            ],
        ),
    ]
